select  DISTINCT
C.COLUMN_NAME, 
		DATA_TYPE +  (CASE
		WHEN DATA_TYPE = 'varchar' THEN  '(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(20)) + ')'
		WHEN DATA_TYPE= 'decimal' THEN  '(' + CAST(NUMERIC_PRECISION AS VARCHAR(20))+ ','+ CAST(NUMERIC_SCALE AS VARCHAR(20)) + ')'
		ELSE '' END),
		CASE WHEN C.IS_NULLABLE = 'YES' THEN '' else 'x' end
 from INFORMATION_SCHEMA.COLUMNS c
 where C.table_name ='Securities'


CASE WHEN   K.COLUMN_NAME  = NULL  THEN 0
ELSE 1 END
 
 SELECT * 
 from INFORMATION_SCHEMA.COLUMNS c
 LEFT JOIN  INFORMATION_SCHEMA.TABLE_CONSTRAINTS  CONSTRAINTS ON CONSTRAINTS.TABLE_NAME = C.TABLE_NAME
LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS K ON CONSTRAINTS.TABLE_NAME = K.TABLE_NAME
                                                         AND CONSTRAINTS.CONSTRAINT_CATALOG = K.CONSTRAINT_CATALOG
                                                         AND CONSTRAINTS.CONSTRAINT_SCHEMA = K.CONSTRAINT_SCHEMA
                                                         AND CONSTRAINTS.CONSTRAINT_NAME = K.CONSTRAINT_NAME
														   AND K.COLUMN_NAME = C.COLUMN_NAME AND CONSTRAINTS.CONSTRAINT_TYPE = 'PRIMARY KEY'
--WHERE   C.CONSTRAINT_TYPE = 'PRIMARY KEY'
--        AND K.COLUMN_NAME = 'keycol';
where C.table_name ='Customers'

SELECT * FROM SYS.COLUMNS
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE

select  COLUMN_NAME, DATA_TYPE,*
 from INFORMATION_SCHEMA.COLUMNS
where table_name ='accounts'